<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Con_jadwal extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        //$this->load->model('Model_main');
        //$this->load->model('Model_rfid');
        $this->load->model('Model_jadwal');
        $this->load->model('Model_monitoring');
        $this->load->library('form_validation');        
        $this->load->library('datatables');
        $this->load->library('template');
        $this->load->library('table');
        date_default_timezone_set('Asia/Jakarta');

        //session
        if(!$this->session->userdata('user_id')){
             redirect('login_page.html');
        }
        $this->load->helper('url');
    }
    public function cek_data(){
        $ip=$this->Model_siswa->get_real_ip();
        print_r($ip);
    }

    public function list_manajemen_jadwal()
    {   

        $tahun_baru = date('Y');
        $data_tahun_baru = array(
            'tahun_ajaran_id'           => $tahun_baru,
            'tahun_ajaran_nama'         => $tahun_baru,
            'tahun_ajaran_is_active'    => 0
        );

        //print_r($data_tahun_baru);
        $insert_tahun_1 = $this->db->insert_string('tahun_ajaran', $data_tahun_baru);
        $insert_tahun_2 = str_replace('INSERT INTO','INSERT IGNORE INTO',$insert_tahun_1);
        $this->db->query($insert_tahun_2);
        //$this->Model_jadwal->insert_tahun_ajaran($tahun_baru);

        $data['list_tahun']     = $this->Model_jadwal->list_tahun();
        $data['list_semester']  = $this->Model_jadwal->list_semester();
        $this->template->display('jadwal/list_jadwal', $data);
    }

    public function aktifkan_semester()
    {
        $id_smt = $this->input->get('id');
        echo $id_smt;
        $this->Model_jadwal->nonaktifkan_semua_smt();
        $this->Model_jadwal->aktifkan_semester($id_smt);

        if ($id_smt == 1) {
            $this->Model_jadwal->ubah_smt_ganjil_1();
            $this->Model_jadwal->ubah_smt_ganjil_3();
            $this->Model_jadwal->ubah_smt_ganjil_5();
            $this->Model_jadwal->non_aktifkan_semua_smt();
            $this->Model_jadwal->aktifkan_semester_id_ganjil();
        }elseif ($id_smt == 2) {
            $this->Model_jadwal->ubah_smt_genap_2();
            $this->Model_jadwal->ubah_smt_genap_4();
            $this->Model_jadwal->ubah_smt_genap_6();
            $this->Model_jadwal->non_aktifkan_semua_smt();
            $this->Model_jadwal->aktifkan_semester_id_genap();
        }
        

        


        


        $this->session->set_flashdata('message',
                                                '<div class="alert bg-success alert-styled-left">
                                                    <button type="button" class="close" data-dismiss="alert">
                                                        <span>×</span>
                                                        <span class="sr-only">Close</span>
                                                    </button>
                                                    <span class="text-semibold">Semeter berhasil diaktifkan</span>
                                                </div>');
        redirect('jadwal.html');
    }

    public function aktifkan_tahun_ajaran()
    {
        $id_tahun_ajaran = $this->input->get('id');
        //echo $id_tahun_ajaran;

        $this->Model_jadwal->nonaktifkan_semua_tahun_ajaran();
        $this->Model_jadwal->aktifkan_tahun_ajaran($id_tahun_ajaran);

        $this->session->set_flashdata('message',
                                                '<div class="alert bg-primary alert-styled-left">
                                                    <button type="button" class="close" data-dismiss="alert">
                                                        <span>×</span>
                                                        <span class="sr-only">Close</span>
                                                    </button>
                                                    <span class="text-semibold">Tahun ajaran berhasil diaktifkan</span>
                                                </div>');
        redirect('jadwal.html');
    }
    

    
}




/* End of file Con_siswa.php */
/* Location: ./application/controllers/Con_siswa.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-11 10:17:16 */
/* http://harviacode.com */
